### ISSUE TITLE
add local mirror for installing icudt

### ISSUE THREAD

**Issue by Mullefa** [Rexamine/stringi#141]
Relates to [this](http://stackoverflow.com/questions/27553452/how-to-install-stringi-library-from-archive-and-install-the-local-icu52l-zip) issue on SO. 

`stri_install_icudt()` can not use local mirrors to install icudt.

[Here](https://gist.github.com/zero323/338c8fb0faf46e5ac06d) is one patch by zero323.

A bit of context: this is a problem for me, as I am using a package I have created - [vepr](https://github.com/Mullefa/vepr) - to deploy code to production. In summary, the proxy is set - via httr - at the function level, however, icudt is installed from a remote using `download.file()` which does not recognize the proxy has been set, and hence causes the installation to hang.

**Comment by gagolews** [comment]
@Mullefa, I can't add `/tmp` to the search path, as not everybody is on a unix-like operating system.
Have you read the `download.file` man page, `Proxy` subsection?

The `http_proxy` environmental variable may be set accordingly (via `Sys.setenv`).

HTH

**Comment by Mullefa** [comment]
Would you consider making the local mirror dependent on the operating system?

**Comment by gagolews** [comment]
Fixing the `/tmp` dir for everybody does not seem as a good idea.

Will you be happy with a new `./configure` script argument that indicates where a local copy of icudt can be found (`/tmp` in particular)? Then, the path could be provided via the `configure.args` arg to the `install.packages` function?

**Comment by gagolews** [comment]
A solution:

`install.packages("stringi", configure.vars=list(ICUDT_DIR="<dir_to_copy_icudt_from>"))`

**Comment by bruceredmon** [comment]
This is does not seem to be fixed in stringi_1.1.1.  Please see issue #229
