### ISSUE TITLE
stri_pad and stri_wrap should allow also relying on code point widths

### ISSUE THREAD

**Issue by yutannihilation** [Rexamine/stringi#149]
Thanks for this great package!

I've faced a problem with `knitr::kable()` which uses `stringr::str_pad()` inside (https://github.com/yihui/knitr/issues/980). East Asian people use so-called "full-width" characters, which is twice as wide as other characters like Alphabets.

`nchar()` considers East Asian Width when `type = 'width'` is specified. For example,

```r
nchar('ツ')
#> [1] 1
nchar('ツ', type = 'width')
#> [1] 2
```

This C function is used in `nchar()`: https://github.com/wch/r-source/blob/0abd43ec8fe03137b98756f7b22608728b76584e/src/main/rlocale.c#L114

It would be great if I could use some similar option for `stri_*_pad()`. Sorry, I'm not ready to write a pull request; I just report this for a gentle feature request.

**Comment by gagolews** [comment]
@yutannihilation Sure, good idea.

**Comment by gagolews** [comment]
BTW, This is related to #8

**Comment by gagolews** [comment]
NOTES:

http://www.cl.cam.ac.uk/~mgk25/ucs/wcwidth.c
http://www.unicode.org/reports/tr11/

```
int width = u_getIntPropertyValue(c, UCHAR_EAST_ASIAN_WIDTH);
    return width == U_EA_FULLWIDTH || width == U_EA_WIDE;
```
???

**Comment by yutannihilation** [comment]
@gagolews Thanks for your quick reply! `str_width()` also sounds nice :+1:

**Comment by yutannihilation** [comment]
I tried to create a pull request, but I'm not good at writing C++ :disappointed: 

Am I on the right track?

**Comment by gagolews** [comment]
Thanks, I'll focus on that in due time (a busy period..)

**Comment by gagolews** [comment]
NOTE: This is also the case of the `stri_wrap` function

**Comment by gagolews** [comment]
NOTE: This is also the case of the stri_wrap function
strwrap uses WIDTH only, so stri_wrap should base on width by default.
Even if the current version of str_pad uses length, I guess default behavior of stri_pad should also base on width

**Comment by gagolews** [comment]
@yutannihilation All done. Can you please check if that's what you requested? Thanks.

**Comment by yutannihilation** [comment]
@gagolews Amazing! I've confirmed that `stri_pad()` handles East Asian characters perfectly.

```r
stri_width("ツ")
#> [1] 2
stri_pad_both("ツ", 4)
#> [1] " ツ "
```

Thanks again!
