### ISSUE TITLE
Expose C/C++ API

### ISSUE THREAD

**Issue by Ironholds** [Rexamine/stringi#151]
Stringi contains a ton of awesome C++ string-handling functions! Me likey.

It would be great if it exposed these functions in a way that was linkable-to, a la RcppArmadillo or BH.

As an example: coming from R, doing string extraction in C++ has always been a pain, because you find the first example of [character] and then the second example of [character], and then you substring between first_example and first_example_plus_one - second_example, because everything is relative, and *argh*

Or you could do:

>// [[Rcpp::depends(stringi)]]
#include \<stringi.h\>
[call to stringi's extractor goes here]

**Comment by gagolews** [comment]
related to #88

**Comment by gagolews** [comment]
Oliver, that's a very good idea. I now more or less know how to do it. This feature is scheduled for stringi_0.6. I'm closing this issue as a duplicate of #88.

**Comment by gagolews** [comment]
@Ironholds DONE, see #88

**Comment by Ironholds** [comment]
Sweeet! Thanks!
