### ISSUE TITLE
Conditionally support C++11

### ISSUE THREAD

**Issue by hadley** [Rexamine/stringi#152]
By using `PKG_CXXFLAGS=$(CXX1XSTD)` in Makevars. This enables C++11 support (and hence C99 support) where available - that will suppress (e.g. ) warnings about `long long`s on the CRAN linux test machine, while still allowing use on (e.g.) Snow Leopard (which doesn't have C++11 support)

**Comment by gagolews** [comment]
@hadley I got the `long long` warning issue closed already in #135 

indeed, C++11 is used conditionally (if R >= 3.1 and some ./configure flag is not set)

closing.
