### ISSUE TITLE
`U_FILE_ACCESS_ERROR` on Travis-CI builds

### ISSUE THREAD

**Issue by wibeasley** [Rexamine/stringi#155]
This morning my builds on [Travis](https://travis-ci.org/OuhscBbmc/REDCapR/builds) starting breaking with the error (but not on [AppVeyor](https://ci.appveyor.com/project/wibeasley/redcapr/history), win-builder, or my local Ubuntu 14.04 and Windows 8 machines).  I think this is related to [this point](https://github.com/Rexamine/stringi/blob/023829f50bb7878a2799ac0fc1fee304f864a1c9/src/stri_exception.cpp#L84-L85) in  `/src/stri_exception.cpp`.

The specific error message (with added line breaks) is:
```
The requested ICU resource file cannot be found. 
Possible problem: ICU data has not been downloaded yet. 
Call `stri_install_check()`. (U_FILE_ACCESS_ERROR)
```

Besides my package, I noticed the error message is occurring in two packages by (@Hadley) also that indirectly depend on stringr/stringi.
* https://travis-ci.org/OuhscBbmc/REDCapR/builds/61714076#L1245 (10 hours ago)
* https://travis-ci.org/hadley/ggplot2/builds/61671981#L1830 (7 hours ago)
* https://travis-ci.org/hadley/adv-r/builds/61604761#L1355 (16 hours ago)

I noticed your [stringi build](https://travis-ci.org/Rexamine/stringi/builds/61585337) passed 19 hours ago, and I'm wondering if that was just before something changed with Travis's VMs or something.

Is Travis's OS failing to install the correct ICU library version?  Do you have any advice, such as altering the .travis.yml file?

**Comment by gagolews** [comment]
Perhaps ICUdata download failed. I cannot diagnose the error without having access to full stringi build logs. What about relying on a stringi version from github?

**Comment by wibeasley** [comment]
You're right, @gagolews, and I'm pleasantly surprised.  I didn't think the stringi code was directly involved, since it hadn't changed on CRAN [in 6 months](http://cran.r-project.org/src/contrib/Archive/stringi/).

* I added it, and Travis [passed](https://travis-ci.org/OuhscBbmc/REDCapR/builds/61753136)
* I then removed it, and Travis [failed](https://travis-ci.org/OuhscBbmc/REDCapR/builds/61756544)
* And finally [passed ](https://travis-ci.org/OuhscBbmc/REDCapR/builds/61756986) after reintroducing it to `.travis.yml`.

Thank you.

**Comment by hadley** [comment]
This seems to be an intermittent build failure on travis. I'm getting increasingly disenfranchised by them :(

**Comment by wibeasley** [comment]
> [I think it would be better to fix the root cause.](https://github.com/hadley/adv-r/pull/680#issuecomment-100226279)

I didn't realize that option was available for the disenfranchised.  

Until the proletarian revolution, I thought installing stringi from GitHub was a suitable alternative for the tests to pass so development can continue.
