### ISSUE TITLE
Solaris: pkg-config ICU detection failed

### ISSUE THREAD

**Issue by jeroenooms** [Rexamine/stringi#160]
Can't get this to install on Solaris. Should I pass some vars to configure or make? This seems correct:
```
-bash-3.2# pkg-config --cflags icu-i18n
-I/opt/csw/include
-bash-3.2# pkg-config --cflags icu-uc
-I/opt/csw/include
-bash-3.2# pkg-config --modversion icu-uc
54.1
-bash-3.2# pkg-config --modversion icu-i18n
54.1
```
However installing gives: http://pastebin.com/raw.php?i=EmRdVhV0

**Comment by gagolews** [comment]
What about:

```
R CMD INSTALL latest_github_version_of_stringi.tar.gz 
--configure-args='--disable-cxx11'
```

?

**Comment by jeroenooms** [comment]
Ok i'll try that. But why is it compiling ICU if it is already present on the system?

**Comment by gagolews** [comment]
Your C++ compiler is:

```
/opt/SunProd/studio12u3/solarisstudio12.3/bin/CC
```

Here's how the verification of the most basic ICU-based project ended:
```
checking with pkg-config for ICU4C installed... 54.1
checking for ICU4C >= 50... yes
checking for proper CPPFLAGS, LDFLAGS, and LIBS... done
checking whether we may build a simple ICU-dependent project... no
```

Are you sure ICU4C was build using Sun's CC and not, e.g., gcc? If you are
using openCSW this may be the case. A solution for that is to compile R
from sources using gcc

Here's the source code of a very simple ICU-based app that failed to be
build using compiler flags as generated by `pkg-config` and the
above-mentioned compiler:

```
      #include <unicode/unistr.h>
      #include <unicode/uvernum.h>
      #include <unicode/ptypes.h>
      #include <unicode/uchar.h>
      #include <unicode/utypes.h>
      #include <stdio.h>
      using namespace icu;

      int main() {
        // base tests
        UnicodeString x("abc");
        x = x+x;
        printf(U_ICU_VERSION);

        return 0;
      }])
```

**Comment by gagolews** [comment]
If it is not the issue of the compilers' bin outs incompatibilies (g++ icu, R package build with CC or inversely), It will also be worth to check if a fix to #164 solves this problem.

**Comment by gagolews** [comment]
@jeroenooms Needs update: Is this still an issue ?

**Comment by jeroenooms** [comment]
I never got this package to work on solaris. Maybe @gaborcsardi can help out with giving you an account on his solaris test box?

**Comment by gagolews** [comment]
OK, I can look at this in more detail.
I'm frequently testing stringi on 2 Solaris machines (including one with Spark CPUs), btw.
