### ISSUE TITLE
Allow forcing the use of system icu

### ISSUE THREAD

**Issue by gagolews** [Rexamine/stringi#165]
A new `./configure` option `--disable-icu-bundle` force the use of system ICU on package build.
This is related to #162 and https://github.com/hadley/stringr/issues/68

**Comment by jeroenooms** [comment]
This should be the default.

**Comment by gagolews** [comment]
But what about Windows and OS X users?

Such an option can also be passed while a call to `install.packages` or `R CMD INSTALL`...

**Comment by jeroenooms** [comment]
On OSX you can link to `libicucore.dynlib`. On windows you are not running `./configure` anyway right?

**Comment by gagolews** [comment]
the cran OS X machines haven't got a sufficiently new version of icu installed :(

**Comment by jeroenooms** [comment]
How do you know? It seems fine on my local osx?

**Comment by gagolews** [comment]
quoting http://www.r-project.org/nosvn/R.check/r-devel-osx-x86_64-clang/stringi-00install.html:

```
checking with pkg-config for ICU4C installed... no
*** The pkg-config script did not detect ICU4C-devel libraries installed
*** We will build ICU4C from sources
```

**Comment by jeroenooms** [comment]
OSX does include libicu, it just does not include the headers. So if you just bundle the `include/unicode` headers that's all you need.

**Comment by gagolews** [comment]
not really, these header files are incompatible between different icu versions

**Comment by jeroenooms** [comment]
Mmm okay that might be a problem.

**Comment by jeroenooms** [comment]
At least on Linux, I think the default should be this. When the configure script cannot find headers, it could exit with an error message like: 

> libicu headers not found. Either install libicu-dev or install package with `--enable-icu-bundle`

.

**Comment by gagolews** [comment]
The default is to use pkg-config and if it fails, try using the icu bundle. Look at this way: this adds one more "degree of freedom" :)

**Comment by jeroenooms** [comment]
So that means we keep having the stringr/travis bug for people who forget to install `libicu-dev`?

**Comment by gagolews** [comment]
I'll work on that.

BTW, how to install libicu-dev on travis?

**Comment by jeroenooms** [comment]
You add it under `apt_packages`, see eg: https://github.com/jeroenooms/curl/blob/master/.travis.yml

**Comment by jeroenooms** [comment]
Unless you are super sure you fix the `U_FILE_ACCESS_ERROR` problem, it should not fall back on bundled version. Under no circumstance should stringi install a non working version of ICU on the system.

**Comment by gagolews** [comment]
Jeroen, If I were to choose between "forgetful users" who didn't install libicu-dev on travis machines and Brian Ripley, I'd choose the latter. And so I do.

The package does not install anything on the system. It just builds icu from sources and links icu statically with `stringi.so`. The problem is related with `icudt` (funny thing: it fails only from time to time). and I'll work on that. Yet, we have a fix now -- on travis machines, libicu-dev must be installed. For now, could you post an instruction on how to use stringr/stringi with travis (what are the prerequisites)? Thanks.

**Comment by jeroenooms** [comment]
OK i'm sorry don't want to be rude, but want to make sure this gets solved properly because it is taking down my entire stack.

**Comment by gagolews** [comment]
OK, I understand. Again, does installing libicu-dev everythere help now?

**Comment by jeroenooms** [comment]
Part of the problem might be that R packages on Ubuntu do not have a fixed location. So they might get built in one dir and then moved over to another. Are you hardcoding the path to `icudt` at build time?

**Comment by jeroenooms** [comment]
I checked that autoconf now picks up on `libicu-dev` at least on Ubuntu. Don't know about other systems.

**Comment by gagolews** [comment]
> I checked that autoconf now picks up on libicu-dev at least on Ubuntu. 

Jolly good!

> Part of the problem might be that R packages on Ubuntu do not have a fixed location. So they might get built in one dir and then moved over to another. Are you hardcoding the path to icudt at build time?

No, I'm not hardcoding the path. But thanks for your remark - you gave me some hint. I now force the load of icudt on stringi dynlib load. I'm pretty sure this solves all the travis problems. Could you test my hypothesis? Thanks!

**Comment by gagolews** [comment]
I checked stringr with `.travis.yml` settings like:

```
language: r
warnings_are_errors: true
sudo: required
r_github_packages:
  - Rexamine/stringi
```

Works like a charm now.
