### ISSUE TITLE
Build should fail when download of icudt fails

### ISSUE THREAD

**Issue by jeroenooms** [Rexamine/stringi#168]
One reason why people have been getting [`The requested ICU resource file cannot be found`](https://github.com/hadley/stringr/issues/68) is because they are using the `r-cran-stringi` package. This package does not work because launchpad builds all packages offline, and therefore downloading `icudt` fails. From the [build log](https://launchpad.net/~marutter/+archive/ubuntu/c2d4u/+build/6646111):

```
make[1]: Leaving directory `/build/buildd/stringi-0.4-1/src'
make[1]: Entering directory `/build/buildd/stringi-0.4-1/src'
make[1]: Leaving directory `/build/buildd/stringi-0.4-1/src'
installing via 'install.libs.R' to /build/buildd/stringi-0.4-1/debian/r-cran-stringi/usr/lib/R/site-library/stringi
downloading ICU data library (icudt)
the files will be extracted to: /build/buildd/stringi-0.4-1/debian/r-cran-stringi/usr/lib/R/site-library/stringi/libs
no icudt in a local repo
trying URL 'http://static.rexamine.com/packages/icudt52l.zip'
Warning in download.file(href, outfname, mode = "wb") :
  unable to resolve 'static.rexamine.com'
Error in download.file(href, outfname, mode = "wb"): cannot open URL 'http://static.rexamine.com/packages/icudt52l.zip'

trying URL 'http://www.mini.pw.edu.pl/~gagolews/stringi/icudt52l.zip'
Warning in download.file(href, outfname, mode = "wb") :
  unable to resolve 'www.mini.pw.edu.pl'
Error in download.file(href, outfname, mode = "wb"): cannot open URL 'http://www.mini.pw.edu.pl/~gagolews/stringi/icudt52l.zip'

trying URL 'http://www.ibspan.waw.pl/~gagolews/stringi/icudt52l.zip'
Warning in download.file(href, outfname, mode = "wb") :
  unable to resolve 'www.ibspan.waw.pl'
Error in download.file(href, outfname, mode = "wb"): cannot open URL 'http://www.ibspan.waw.pl/~gagolews/stringi/icudt52l.zip'

icudt download failed
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (stringi)
```

This problem is now partially fixed for ubuntu because we can use the system `libicu-dev` when available, but for other platforms this is still problematic. It seems to me that the installation should fail when the download fails to prevent installation and shipping of non working packages.

**Comment by gagolews** [comment]
Good idea, thanks!

**Comment by jeroenooms** [comment]
You can easily catch such errors by adding something trivial to `onLoad` that actually uses the package. Thereby you confirm that the package is actually working when it does `** testing if installed package can be loaded`

**Comment by gagolews** [comment]
@jeroenooms fixed now

**Comment by jeroenooms** [comment]
Okay thanks. As you know I really think it is a bad idea to install half-functioning packages but I guess we are not going to agree on that:

```
# Note that if the data file is not found, some features will
# be unavailable (but the package itself will load properly,
# and UCD-independent functions will work properly)
```

**Comment by gagolews** [comment]
That's just a very old comment, install now fails if icudt is unavailable.

**Comment by jeroenooms** [comment]
Oh okay sorry, from the commit it looks like this comment was added. 

Could you consider my other suggestion of adding something in `onLoad` or `onAttach` that uses `icudt` so that we are super duper sure that everything absolutely works when the package is installed?

**Comment by gagolews** [comment]
a side effect of changes made in c651d31affcebd4402e93b21eeb5b0fcfd776ff6 (forced `u_init` call) is that this is also checked on stringi dynlib load

**Comment by jeroenooms** [comment]
Alright I usually prefer an explicit little test, but I'll take your word on this then :)

**Comment by jeroenooms** [comment]
Going to try to build the new opencpu stack on different platforms, fingers crossed...

**Comment by Titolondon** [comment]
It's working.. Installation failed because it cannot download icudt.
How could I update stringi when my rstudio server is offline?
Thanks.

**Comment by gagolews** [comment]
A possible way to do so is to install libicu-dev or libicu-devel on your Linux distribution, see the `INSTALL` file for more details.

**Comment by HenrikBengtsson** [comment]
Found this trhead after running into to installation issues (full details below) with stringi in a CentOS 7.4 environment **without internet access**.  From the comments in the thread, it looks like I should not expect `install.packages("stringi", repos = "file://...")` to work - is that correct?  Or should I attempt to install some missing library (I need to run this by sysadm so hence no trial'n'error before ask here).

Also, couldn't the `stringi` installation fall back to look for a local copy of the `icudt55l.zip` file, say, in the current directory, or probably better, in a directory pointed to by `STRINGI_DOWNLOADS`?

```r
> install.packages("stringi", repos = "file://...")
[...]
* installing *source* package 'stringi' ...
** package 'stringi' successfully unpacked and MD5 sums checked
checking for local ICUDT_DIR... icu55/data
checking for R_HOME... /netapp/home/hb/shared/apps/manual/r/R-3.4.2-20171108/lib64/R
checking for R... /netapp/home/hb/shared/apps/manual/r/R-3.4.2-20171108/lib64/R/bin/R
checking for R >= 3.1.0 for C++11 use... yes
checking for R < 3.4.0 for CXX1X flag use... no
checking for cat... /bin/cat
checking for gcc... gcc -std=gnu99
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc -std=gnu99 accepts -g... yes
checking for gcc -std=gnu99 option to accept ISO C89... none needed
checking how to run the C preprocessor... g++ -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking elf.h usability... yes
checking elf.h presence... yes
checking for elf.h... yes
checking whether we are using the GNU C++ compiler... yes
checking whether g++ -std=gnu++11 accepts -g... yes
checking whether the C++ compiler supports the long long type... yes
checking whether the compiler implements namespaces... yes
checking whether the compiler supports Standard Template Library... yes
checking whether std::map is available... yes
checking for pkg-config... /bin/pkg-config
checking with pkg-config for the system ICU4C... 50.1.2
checking for ICU4C >= 52... no
*** ICU4C 50.1.2 has been detected
*** Minimal requirements, i.e., ICU4C >= 52, are not met
*** Trying with "standard" fallback flags
checking whether we may build an ICU4C-based project... yes
checking programmatically for sufficient U_ICU_VERSION_MAJOR_NUM... no
*** The available ICU4C cannot be used
checking whether we may compile src/icu55/common/umapfile.c... yes
checking whether we may compile src/icu55/common/putil.cpp... yes
checking whether we can fetch icudt... downloading the ICU data library (icudt)
output path: icu55/data/icudt55l.zip
trying URL 'https://raw.githubusercontent.com/gagolews/stringi/master/src/icu55/data/icudt55l.zip'
Error in download.file(paste(href, fname, sep = ""), icudtzipfname, mode = "wb"): cannot open URL 'https://raw.githu
busercontent.com/gagolews/stringi/master/src/icu55/data/icudt55l.zip'

trying URL 'http://www.mini.pw.edu.pl/~gagolews/stringi/icudt55l.zip'
Error in download.file(paste(href, fname, sep = ""), icudtzipfname, mode = "wb"): cannot open URL 'http://www.mini.p
w.edu.pl/~gagolews/stringi/icudt55l.zip'

trying URL 'http://www.ibspan.waw.pl/~gagolews/stringi/icudt55l.zip'
Error in download.file(paste(href, fname, sep = ""), icudtzipfname, mode = "wb"): cannot open URL 'http://www.ibspan
.waw.pl/~gagolews/stringi/icudt55l.zip'

icudt download failed
Error: Stopping on error
In addition: Warning messages:
1: In download.file(paste(href, fname, sep = ""), icudtzipfname, mode = "wb") :
  URL 'https://raw.githubusercontent.com/gagolews/stringi/master/src/icu55/data/icudt55l.zip': status was 'Couldn't 
resolve host name'
2: In download.file(paste(href, fname, sep = ""), icudtzipfname, mode = "wb") :
  URL 'http://www.mini.pw.edu.pl/~gagolews/stringi/icudt55l.zip': status was 'Couldn't resolve host name'
3: In download.file(paste(href, fname, sep = ""), icudtzipfname, mode = "wb") :
  URL 'http://www.ibspan.waw.pl/~gagolews/stringi/icudt55l.zip': status was 'Couldn't resolve host name'
Execution halted
*** icudt could not be downloaded. stopping.
ERROR: configuration failed for package 'stringi'
* removing '/netapp/home/hb/R/x86_64-pc-linux-gnu-library/3.4/stringi'
* restoring previous '/netapp/home/hb/R/x86_64-pc-linux-gnu-library/3.4/stringi'
Warning message:
In install.packages("stringi") :
  installation of package 'stringi' had non-zero exit status

```

**Comment by jeroen** [comment]
@HenrikBengtsson did you try installing `yum install libicu-devel` and build against that? That used to work. Or did the required icu version bump again?

**Comment by HenrikBengtsson** [comment]
I don't have `sudo` so trying to install new libraries will be a slow process.  I think I've got the latest version of `libicu-devel`;
```sh
$ yum info libicu-devel
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
Installed Packages
Name        : libicu-devel
Arch        : x86_64
Version     : 50.1.2
Release     : 15.el7
Size        : 3.9 M
Repo        : installed
From repo   : anaconda
Summary     : Development files for International Components for Unicode
URL         : http://www.icu-project.org/
License     : MIT and UCD and Public Domain
Description : Includes and definitions for developing with icu.

Available Packages
Name        : libicu-devel
Arch        : i686
Version     : 50.1.2
Release     : 15.el7
Size        : 702 k
Repo        : qb3-base/x86_64
Summary     : Development files for International Components for Unicode
URL         : http://www.icu-project.org/
License     : MIT and UCD and Public Domain
Description : Includes and definitions for developing with icu.
```

**Comment by jeroen** [comment]
Ah I see that stringi `1.1.5` has bumped the requirement to ICU 52. That's unfortunate. You can try installing `stringi 1.1.4`?

**Comment by cderv** [comment]
The source of ICU should be included in the github repository of stringi. If you download the repo as zip directory from an online environment then copy to your offline environment and install from source it should work.  It did for me.

**Comment by HenrikBengtsson** [comment]
Confirming that that's why / a workaround.  I can that `stringi 1.1.3` works with:
```r
checking with pkg-config for ICU4C installed... 50.1.2
checking for ICU4C >= 50... yes
checking for proper CPPFLAGS, LDFLAGS, and LIBS... done
```
whereas `stringi 1.1.5` does not:
```r
checking with pkg-config for the system ICU4C... 50.1.2
checking for ICU4C >= 52... no
*** ICU4C 50.1.2 has been detected
*** Minimal requirements, i.e., ICU4C >= 52, are not met
[...]
```

I ran into this problem with `revdepcheck()`, which means I cannot really control the version installed (unless I fake the CRAN package content etc).  However, since it relies on `crancache`, I could work around the problem by populating its local cache with `crancache::install_packages("stringi")` (on a machine with internet access).

Regardless whether I'm savvy enough to work around this myself using various hacks, installing ICU from source locally and setting up the proper `LD_LIBRARY_PATH` etc, I'd like to push for the suggestion I made above:  **Have the stringi installer to look for a local `icudt55l.zip` file** - I think this will help less savvy users on these type of environment (e.g. academic / research HPC) and the instructions will be very simple (e.g. "Download `https://.../icudt55l.zip` and retry") - those could even be mentioned in the installation error message.

As a related side note: I think offline run-time usage and testing (`R CMD check --as-cran`) is something I think CRAN should report on and help maintainers to strive for.  The poor man's version would be to flag internet access as a requirement in a package `DESCRIPTION` file.

**Comment by cderv** [comment]
> Have the stringi installer to look for a local icudt55l.zip file

You can already do this using an environment variable or putting it the correct dir under src like it is in this github repo. 

See my answer just above.

**Comment by HenrikBengtsson** [comment]
Great - thxs @cderv. `ICUDT_DIR` is what I was looking for.  I know see that there's a https://cran.r-project.org/web/packages/stringi/INSTALL with this information (it also mentions installation from the git source).  AFAIU, the following should work:

Download:
```r
{open}$ cd /abs/path/to
{open}$ curl -O https://raw.githubusercontent.com/gagolews/stringi/master/src/icu55/data/icudt55l.zip
{open}$ 
```
Verify and install:
```r
{restricted}$ export ICUDT_DIR=/abs/path/to
{restricted}$ ls -l $ICUDT_DIR/icudt55l.zip
-rw-r--r--. 1 hb lsd 10176327 Dec 16 15:43 /abs/path/to/icudt55l.zip
{restricted}$ md5sum $ICUDT_DIR/icudt55l.zip
ff345529f230cc39bb8d450af0607708  /abs/path/to/icudt55l.zip
{restricted}$ Rscript -e "install.packages('stringi')"
[...]
checking with pkg-config for the system ICU4C... 50.1.2
checking for ICU4C >= 52... no
*** ICU4C 50.1.2 has been detected
*** Minimal requirements, i.e., ICU4C >= 52, are not met
*** Trying with "standard" fallback flags
checking whether we may build an ICU4C-based project... yes
checking programmatically for sufficient U_ICU_VERSION_MAJOR_NUM... no
*** The available ICU4C cannot be used
checking whether we may compile src/icu55/common/umapfile.c... yes
checking whether we may compile src/icu55/common/putil.cpp... yes
checking whether we can fetch icudt... icudt already downloaded
configure: creating ./config.status
config.status: creating src/Makevars
config.status: creating src/uconfig_local.h
config.status: creating src/install.libs.R

*** stringi configure summary:
    ICU_FOUND=0
    ICUDT_DIR=/abs/path/to
[...]
```

The nice thing with `ICUDT_DIR` is that sysadm can set it (as long it's maintained, because if the file does not exist `stringi` will give a false `md5sum mismatch` error), and all users can install `stringi` out of the box from CRAN.

**Comment by cderv** [comment]
Agreed, `ICUDT_DIR` configuration is a good solution.

Know that you can also create a `stringi` package source (`tar.gz`) that contains the zip file in `src/icu55/data` by commenting the correct line in `.Rbuildignore` and building the `tar.gz` source packaging.
When you have that, anyone will be able to install it from source using this `tar.gz` file. You can also publish this package in a custom and internal cran-like repo. `install.package("stringi", repo ="cran_like_url")` will work.
