### ISSUE TITLE
Build fails on OpenBSD [Misconfigured R C++11 compiler settings]

### ISSUE THREAD

**Issue by pschmied** [Rexamine/stringi#169]
Hello,

Just reporting a build failure on OpenBSD. The first thing I notice, is that the `configure` script seems to not be finding the c++ compiler:

    > install.packages("~/tmp/stringi", repos=NULL, type="source")
    Installing package into '/home/peter/R/x86_64-unknown-openbsd5.8-library/3.2'
    (as 'lib' is unspecified)
    * installing *source* package 'stringi' ...
    checking for local ICUDT_DIR... icu55/data
    checking for R_HOME... /usr/local/lib/R
    checking for R... /usr/local/lib/R/bin/R
    checking for R >= 3.1.0... yes
    checking for cat... /bin/cat
    ./configure[2396]: "/usr/local/lib/R/bin/R": not found
    ./configure[2396]: "/usr/local/lib/R/bin/R": not found
    checking for gcc... cc -std=gnu99
    checking whether the C compiler works... yes
    checking for C compiler default output file name... a.out
    checking for suffix of executables... 
    checking whether we are cross compiling... no
    checking for suffix of object files... o
    checking whether we are using the GNU C compiler... yes
    checking whether cc -std=gnu99 accepts -g... yes
    checking for cc -std=gnu99 option to accept ISO C89... none needed
    checking whether we are using the GNU C++ compiler... no
    checking whether   accepts -g... no
    checking how to run the C++ preprocessor... /lib/cpp
    configure: error: in `/home/peter/tmp/stringi':
    configure: error: C++ preprocessor "/lib/cpp" fails sanity check
    See `config.log' for more details
    ERROR: configuration failed for package 'stringi'
    * removing '/home/peter/R/x86_64-unknown-openbsd5.8-library/3.2/stringi'
    Warning message:
    In install.packages("~/tmp/stringi", repos = NULL, type = "source") :
      installation of package '/home/peter/tmp/stringi' had non-zero exit status

However, gcc is definitely there as part of the base system:

    % which g++
    /usr/bin/g++
    % which cpp
    /usr/bin/cpp

I'm including the config.log, in hopes that it may provide some clue as to the issue.

=========================================
config.log
=========================================

    This file contains any messages produced by compilers while
    running configure, to aid debugging if configure makes a mistake.

    It was created by stringi configure 0.5, which was
    generated by GNU Autoconf 2.69.  Invocation command line was

      $ ./configure 

    ## --------- ##
    ## Platform. ##
    ## --------- ##

    hostname = XXXXXXXXXX.comcast.net.
    uname -m = amd64
    uname -r = 5.8
    uname -s = OpenBSD
    uname -v = GENERIC.MP#1090

    /usr/bin/uname -p = amd64
    /bin/uname -X     = unknown

    /bin/arch              = unknown
    /usr/bin/arch -k       = OpenBSD.amd64
    /usr/convex/getsysinfo = unknown
    /usr/bin/hostinfo      = unknown
    /bin/machine           = unknown
    /usr/bin/oslevel       = unknown
    /bin/universe          = unknown

    PATH: /home/peter/perl5/bin
    PATH: /home/peter/.cabal/bin
    PATH: /bin
    PATH: /usr/bin
    PATH: /sbin
    PATH: /usr/sbin
    PATH: /usr/X11R6/bin
    PATH: /usr/local/bin
    PATH: /usr/local/sbin
    PATH: /usr/local/jdk-1.7.0/bin

    ## ----------- ##
    ## Core tests. ##
    ## ----------- ##

    configure:2260: checking for local ICUDT_DIR
    configure:2265: result: icu55/data
    configure:2270: checking for R_HOME
    configure:2281: result: /usr/local/lib/R
    configure:2287: checking for R
    configure:2297: result: /usr/local/lib/R/bin/R
    configure:2300: checking for R >= 3.1.0
    configure:2304: result: yes
    configure:2320: checking for cat
    configure:2338: found /bin/cat
    configure:2350: result: /bin/cat
    configure:2458: checking for gcc
    configure:2485: result: cc -std=gnu99
    configure:2714: checking for C compiler version
    configure:2723: cc -std=gnu99 --version >&5
    cc (GCC) 4.2.1 20070719 
    Copyright (C) 2007 Free Software Foundation, Inc.
    This is free software; see the source for copying conditions.  There is NO
    warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

    configure:2734: $? = 0
    configure:2723: cc -std=gnu99 -v >&5
    Reading specs from /usr/lib/gcc-lib/amd64-unknown-openbsd5.8/4.2.1/specs
    Target: amd64-unknown-openbsd5.8
    Configured with: OpenBSD/amd64 system compiler
    Thread model: posix
    gcc version 4.2.1 20070719 
    configure:2734: $? = 0
    configure:2723: cc -std=gnu99 -V >&5
    cc: '-V' must come at the start of the command line
    configure:2734: $? = 1
    configure:2723: cc -std=gnu99 -qversion >&5
    cc: unrecognized option '-qversion'
    cc: no input files
    configure:2734: $? = 1
    configure:2754: checking whether the C compiler works
    configure:2776: cc -std=gnu99 -O2 -pipe  -I/usr/local/include/ereadline -I/usr/local/include  -UDEBUG -DNDEBUG   conftest.c   >&5
    configure:2780: $? = 0
    configure:2828: result: yes
    configure:2831: checking for C compiler default output file name
    configure:2833: result: a.out
    configure:2839: checking for suffix of executables
    configure:2846: cc -std=gnu99 -o conftest -O2 -pipe  -I/usr/local/include/ereadline -I/usr/local/include  -UDEBUG -DNDEBUG   conftest.c   >&5
    configure:2850: $? = 0
    configure:2872: result: 
    configure:2894: checking whether we are cross compiling
    configure:2902: cc -std=gnu99 -o conftest -O2 -pipe  -I/usr/local/include/ereadline -I/usr/local/include  -UDEBUG -DNDEBUG   conftest.c   >&5
    configure:2906: $? = 0
    configure:2913: ./conftest
    configure:2917: $? = 0
    configure:2932: result: no
    configure:2937: checking for suffix of object files
    configure:2959: cc -std=gnu99 -c -O2 -pipe  -I/usr/local/include/ereadline -I/usr/local/include  -UDEBUG -DNDEBUG conftest.c >&5
    configure:2963: $? = 0
    configure:2984: result: o
    configure:2988: checking whether we are using the GNU C compiler
    configure:3007: cc -std=gnu99 -c -O2 -pipe  -I/usr/local/include/ereadline -I/usr/local/include  -UDEBUG -DNDEBUG conftest.c >&5
    configure:3007: $? = 0
    configure:3016: result: yes
    configure:3025: checking whether cc -std=gnu99 accepts -g
    configure:3045: cc -std=gnu99 -c -g -I/usr/local/include/ereadline -I/usr/local/include  -UDEBUG -DNDEBUG conftest.c >&5
    configure:3045: $? = 0
    configure:3086: result: yes
    configure:3103: checking for cc -std=gnu99 option to accept ISO C89
    configure:3166: cc -std=gnu99  -c -O2 -pipe  -I/usr/local/include/ereadline -I/usr/local/include  -UDEBUG -DNDEBUG conftest.c >&5
    configure:3166: $? = 0
    configure:3179: result: none needed
    configure:3317: checking for C++ compiler version
    configure:3326:   --version >&5
    ./configure: --version: not found
    configure:3337: $? = 127
    configure:3326:   -v >&5
    ./configure: -v: not found
    configure:3337: $? = 127
    configure:3326:   -V >&5
    ./configure: -V: not found
    configure:3337: $? = 127
    configure:3326:   -qversion >&5
    ./configure: -qversion: not found
    configure:3337: $? = 127
    configure:3341: checking whether we are using the GNU C++ compiler
    configure:3360:   -c   -I/usr/local/include/ereadline -I/usr/local/include  -UDEBUG -DNDEBUG conftest.cpp >&5
    ./configure: -c: not found
    configure:3360: $? = 127
    configure: failed program was:
    | /* confdefs.h */
    | #define PACKAGE_NAME "stringi"
    | #define PACKAGE_TARNAME "stringi"
    | #define PACKAGE_VERSION "0.5"
    | #define PACKAGE_STRING "stringi 0.5"
    | #define PACKAGE_BUGREPORT "stringi@rexamine.com"
    | #define PACKAGE_URL ""
    | /* end confdefs.h.  */
    | 
    | int
    | main ()
    | {
    | #ifndef __GNUC__
    |        choke me
    | #endif
    | 
    |   ;
    |   return 0;
    | }
    configure:3369: result: no
    configure:3378: checking whether   accepts -g
    configure:3398:   -c -g -I/usr/local/include/ereadline -I/usr/local/include  -UDEBUG -DNDEBUG conftest.cpp >&5
    ./configure: -c: not found
    configure:3398: $? = 127
    configure: failed program was:
    | /* confdefs.h */
    | #define PACKAGE_NAME "stringi"
    | #define PACKAGE_TARNAME "stringi"
    | #define PACKAGE_VERSION "0.5"
    | #define PACKAGE_STRING "stringi 0.5"
    | #define PACKAGE_BUGREPORT "stringi@rexamine.com"
    | #define PACKAGE_URL ""
    | /* end confdefs.h.  */
    | 
    | int
    | main ()
    | {
    | 
    |   ;
    |   return 0;
    | }
    configure:3413:   -c  -I/usr/local/include/ereadline -I/usr/local/include  -UDEBUG -DNDEBUG conftest.cpp >&5
    ./configure: -c: not found
    configure:3413: $? = 127
    configure: failed program was:
    | /* confdefs.h */
    | #define PACKAGE_NAME "stringi"
    | #define PACKAGE_TARNAME "stringi"
    | #define PACKAGE_VERSION "0.5"
    | #define PACKAGE_STRING "stringi 0.5"
    | #define PACKAGE_BUGREPORT "stringi@rexamine.com"
    | #define PACKAGE_URL ""
    | /* end confdefs.h.  */
    | 
    | int
    | main ()
    | {
    | 
    |   ;
    |   return 0;
    | }
    configure:3429:   -c -g -I/usr/local/include/ereadline -I/usr/local/include  -UDEBUG -DNDEBUG conftest.cpp >&5
    ./configure: -c: not found
    configure:3429: $? = 127
    configure: failed program was:
    | /* confdefs.h */
    | #define PACKAGE_NAME "stringi"
    | #define PACKAGE_TARNAME "stringi"
    | #define PACKAGE_VERSION "0.5"
    | #define PACKAGE_STRING "stringi 0.5"
    | #define PACKAGE_BUGREPORT "stringi@rexamine.com"
    | #define PACKAGE_URL ""
    | /* end confdefs.h.  */
    | 
    | int
    | main ()
    | {
    | 
    |   ;
    |   return 0;
    | }
    configure:3439: result: no
    configure:3469: checking how to run the C++ preprocessor
    configure:3496:   -E -I/usr/local/include/ereadline -I/usr/local/include  -UDEBUG -DNDEBUG conftest.cpp
    ./configure: -E: not found
    configure:3496: $? = 127
    configure: failed program was:
    | /* confdefs.h */
    | #define PACKAGE_NAME "stringi"
    | #define PACKAGE_TARNAME "stringi"
    | #define PACKAGE_VERSION "0.5"
    | #define PACKAGE_STRING "stringi 0.5"
    | #define PACKAGE_BUGREPORT "stringi@rexamine.com"
    | #define PACKAGE_URL ""
    | /* end confdefs.h.  */
    | #ifdef __STDC__
    | # include <limits.h>
    | #else
    | # include <assert.h>
    | #endif
    | 		     Syntax error
    configure:3496:   -E -I/usr/local/include/ereadline -I/usr/local/include  -UDEBUG -DNDEBUG conftest.cpp
    ./configure: -E: not found
    configure:3496: $? = 127
    configure: failed program was:
    | /* confdefs.h */
    | #define PACKAGE_NAME "stringi"
    | #define PACKAGE_TARNAME "stringi"
    | #define PACKAGE_VERSION "0.5"
    | #define PACKAGE_STRING "stringi 0.5"
    | #define PACKAGE_BUGREPORT "stringi@rexamine.com"
    | #define PACKAGE_URL ""
    | /* end confdefs.h.  */
    | #ifdef __STDC__
    | # include <limits.h>
    | #else
    | # include <assert.h>
    | #endif
    | 		     Syntax error
    configure:3496: /lib/cpp -I/usr/local/include/ereadline -I/usr/local/include  -UDEBUG -DNDEBUG conftest.cpp
    ./configure: /lib/cpp: not found
    configure:3496: $? = 127
    configure: failed program was:
    | /* confdefs.h */
    | #define PACKAGE_NAME "stringi"
    | #define PACKAGE_TARNAME "stringi"
    | #define PACKAGE_VERSION "0.5"
    | #define PACKAGE_STRING "stringi 0.5"
    | #define PACKAGE_BUGREPORT "stringi@rexamine.com"
    | #define PACKAGE_URL ""
    | /* end confdefs.h.  */
    | #ifdef __STDC__
    | # include <limits.h>
    | #else
    | # include <assert.h>
    | #endif
    | 		     Syntax error
    configure:3496: /lib/cpp -I/usr/local/include/ereadline -I/usr/local/include  -UDEBUG -DNDEBUG conftest.cpp
    ./configure: /lib/cpp: not found
    configure:3496: $? = 127
    configure: failed program was:
    | /* confdefs.h */
    | #define PACKAGE_NAME "stringi"
    | #define PACKAGE_TARNAME "stringi"
    | #define PACKAGE_VERSION "0.5"
    | #define PACKAGE_STRING "stringi 0.5"
    | #define PACKAGE_BUGREPORT "stringi@rexamine.com"
    | #define PACKAGE_URL ""
    | /* end confdefs.h.  */
    | #ifdef __STDC__
    | # include <limits.h>
    | #else
    | # include <assert.h>
    | #endif
    | 		     Syntax error
    configure:3535: result: /lib/cpp
    configure:3555: /lib/cpp -I/usr/local/include/ereadline -I/usr/local/include  -UDEBUG -DNDEBUG conftest.cpp
    ./configure: /lib/cpp: not found
    configure:3555: $? = 127
    configure: failed program was:
    | /* confdefs.h */
    | #define PACKAGE_NAME "stringi"
    | #define PACKAGE_TARNAME "stringi"
    | #define PACKAGE_VERSION "0.5"
    | #define PACKAGE_STRING "stringi 0.5"
    | #define PACKAGE_BUGREPORT "stringi@rexamine.com"
    | #define PACKAGE_URL ""
    | /* end confdefs.h.  */
    | #ifdef __STDC__
    | # include <limits.h>
    | #else
    | # include <assert.h>
    | #endif
    | 		     Syntax error
    configure:3555: /lib/cpp -I/usr/local/include/ereadline -I/usr/local/include  -UDEBUG -DNDEBUG conftest.cpp
    ./configure: /lib/cpp: not found
    configure:3555: $? = 127
    configure: failed program was:
    | /* confdefs.h */
    | #define PACKAGE_NAME "stringi"
    | #define PACKAGE_TARNAME "stringi"
    | #define PACKAGE_VERSION "0.5"
    | #define PACKAGE_STRING "stringi 0.5"
    | #define PACKAGE_BUGREPORT "stringi@rexamine.com"
    | #define PACKAGE_URL ""
    | /* end confdefs.h.  */
    | #ifdef __STDC__
    | # include <limits.h>
    | #else
    | # include <assert.h>
    | #endif
    | 		     Syntax error
    configure:3585: error: in `/home/peter/tmp/stringi':
    configure:3587: error: C++ preprocessor "/lib/cpp" fails sanity check
    See `config.log' for more details

    ## ---------------- ##
    ## Cache variables. ##
    ## ---------------- ##

    ac_cv_c_compiler_gnu=yes
    ac_cv_cxx_compiler_gnu=no
    ac_cv_env_CAT_set=
    ac_cv_env_CAT_value=
    ac_cv_env_CCC_set=
    ac_cv_env_CCC_value=
    ac_cv_env_CC_set=
    ac_cv_env_CC_value=
    ac_cv_env_CFLAGS_set=
    ac_cv_env_CFLAGS_value=
    ac_cv_env_CPPFLAGS_set=
    ac_cv_env_CPPFLAGS_value=
    ac_cv_env_CXXCPP_set=
    ac_cv_env_CXXCPP_value=
    ac_cv_env_CXXFLAGS_set=
    ac_cv_env_CXXFLAGS_value=
    ac_cv_env_CXX_set=
    ac_cv_env_CXX_value=
    ac_cv_env_ICUDT_DIR_set=
    ac_cv_env_ICUDT_DIR_value=
    ac_cv_env_LDFLAGS_set=
    ac_cv_env_LDFLAGS_value=
    ac_cv_env_LIBS_set=
    ac_cv_env_LIBS_value=
    ac_cv_env_PKG_CONFIG_PATH_set=
    ac_cv_env_PKG_CONFIG_PATH_value=
    ac_cv_env_R_HOME_set=set
    ac_cv_env_R_HOME_value=/usr/local/lib/R
    ac_cv_env_build_alias_set=
    ac_cv_env_build_alias_value=
    ac_cv_env_host_alias_set=
    ac_cv_env_host_alias_value=
    ac_cv_env_target_alias_set=
    ac_cv_env_target_alias_value=
    ac_cv_objext=o
    ac_cv_path_CAT=/bin/cat
    ac_cv_prog_CXXCPP=/lib/cpp
    ac_cv_prog_ac_ct_CC='cc -std=gnu99'
    ac_cv_prog_cc_c89=
    ac_cv_prog_cc_g=yes
    ac_cv_prog_cxx_g=no

    ## ----------------- ##
    ## Output variables. ##
    ## ----------------- ##

    CAT='/bin/cat'
    CC='cc -std=gnu99'
    CFLAGS='-O2 -pipe '
    CPPFLAGS='-I/usr/local/include/ereadline -I/usr/local/include  -UDEBUG -DNDEBUG'
    CXX=' '
    CXXCPP='/lib/cpp'
    CXXFLAGS=' '
    DEFS=''
    ECHO_C=''
    ECHO_N='-n'
    ECHO_T=''
    EGREP=''
    EXEEXT=''
    GREP=''
    ICUDT_DIR='icu55/data'
    ICU_FOUND=''
    LDFLAGS=' '
    LIBOBJS=''
    LIBS=' '
    LTLIBOBJS=''
    OBJEXT='o'
    PACKAGE_BUGREPORT='stringi@rexamine.com'
    PACKAGE_NAME='stringi'
    PACKAGE_STRING='stringi 0.5'
    PACKAGE_TARNAME='stringi'
    PACKAGE_URL=''
    PACKAGE_VERSION='0.5'
    PATH_SEPARATOR=':'
    PKG_CONFIG=''
    PKG_CONFIG_PATH=''
    R_HOME='/usr/local/lib/R'
    SHELL='/bin/sh'
    STRINGI_CFLAGS=''
    STRINGI_CPPFLAGS=''
    STRINGI_CXXFLAGS=''
    STRINGI_CXXSTD='CXX_STD=CXX11'
    STRINGI_ICU_COMMON_SOURCES_C=''
    STRINGI_ICU_COMMON_SOURCES_CPP=''
    STRINGI_ICU_I18N_SOURCES_C=''
    STRINGI_ICU_I18N_SOURCES_CPP=''
    STRINGI_ICU_STUBDATA_SOURCES_C=''
    STRINGI_ICU_STUBDATA_SOURCES_CPP=''
    STRINGI_LDFLAGS=''
    STRINGI_LIBS=''
    STRINGI_OBJECTS=''
    STRINGI_SOURCES_CPP=''
    ac_ct_CC='cc -std=gnu99'
    ac_ct_CXX=''
    bindir='${exec_prefix}/bin'
    build_alias=''
    datadir='${datarootdir}'
    datarootdir='${prefix}/share'
    docdir='${datarootdir}/doc/${PACKAGE_TARNAME}'
    dvidir='${docdir}'
    exec_prefix='NONE'
    host_alias=''
    htmldir='${docdir}'
    includedir='${prefix}/include'
    infodir='${datarootdir}/info'
    libdir='${exec_prefix}/lib'
    libexecdir='${exec_prefix}/libexec'
    localedir='${datarootdir}/locale'
    localstatedir='${prefix}/var'
    mandir='${datarootdir}/man'
    oldincludedir='/usr/include'
    pdfdir='${docdir}'
    prefix='NONE'
    program_transform_name='s,x,x,'
    psdir='${docdir}'
    sbindir='${exec_prefix}/sbin'
    sharedstatedir='${prefix}/com'
    sysconfdir='${prefix}/etc'
    target_alias=''

    ## ----------- ##
    ## confdefs.h. ##
    ## ----------- ##

    /* confdefs.h */
    #define PACKAGE_NAME "stringi"
    #define PACKAGE_TARNAME "stringi"
    #define PACKAGE_VERSION "0.5"
    #define PACKAGE_STRING "stringi 0.5"
    #define PACKAGE_BUGREPORT "stringi@rexamine.com"
    #define PACKAGE_URL ""

    configure: exit 1

**Comment by gagolews** [comment]
First of all, let's try disabling C++11. Probably these are R build settings themselves, which are misconfigured:

```
install.packages('stringi', configure.args='--disable-cxx11')
```

Tell me if it works now.

Inspect these default compiler settings with:

```
R CMD config CXX1X
cat /usr/lib64/R/etc/Makeconf | grep CXX1X # /usr/lib64/R -- path with R installation
```

If I am right, you won't be able to install any other C++11-requiring packages...

**Comment by pschmied** [comment]
Many thanks for the reply. Indeed you're correct that the configure flag fixes the problem. I'm feeling a little sheepish right now, because I even tried this previously. Instead of:

    install.packages('stringi', configure.args='--disable-cxx11')

I instead wrote:
    install.packages('stringi', configure.args='disable-cxx11')

Of course this didn't work. Somehow my brain decided `install.packages()` wanted its configure flags without the hyphens.

I wonder if the need to disable-cxx11 could be detected somehow for platforms like OpenBSD? Many thanks for your reply, and for your R package!

**Comment by gagolews** [comment]
Good idea, thanks.

**Comment by gagolews** [comment]
@pschmied I filed a patch - does the latest git version compile cleanly without any additional configure args?

**Comment by pschmied** [comment]
Appears to load without any problems!

**Comment by reactormonk** [comment]
Currently, I get 

    checking whether we are using the GNU C++ compiler... no
    checking whether   accepts -g... no
    checking whether the C++ compiler supports the long long type... no
    *** trying with disabled C++11 compiler
    checking whether the C++ compiler supports the long long type... no
    *** verify your C++ compiler's abilities (long long, STL, etc. support)
    ERROR: configuration failed for package ‘stringi’

on Archlinux. It works with the explicit c++11 disable switch.

**Comment by gagolews** [comment]
can you now try with the most recent git-devel version of stringi?

**Comment by reactormonk** [comment]
Can't install devtools :-/

**Comment by gagolews** [comment]
What about:
```
wget https://github.com/Rexamine/stringi/archive/master.zip
unzip master.zip
R CMD INSTALL stringi-master --preclean
```
?

**Comment by reactormonk** [comment]
Works.

**Comment by gagolews** [comment]
Thx.

**Comment by PoseidonJoseph** [comment]
Hello I had something like this 
checking C++ compiler g++  -O2 -pedantic -fomit-frame-pointer -m64 -mtune=haswell -march=haswell... no
checking C++ compiler g++  ... no
configure: error: C++ compiler not available, see config.log for details
 any help please I'm just starting to Compiling GCC 6 on macOS Sierra

**Comment by gagolews** [comment]
Do you have xcode installed? (https://developer.apple.com/xcode/)

**Comment by PoseidonJoseph** [comment]
Yes , I have xcode installed and command tool line
Thanx you.
I am trying to assembly a C program with terminal mac and it gives me this error also wich I did not have before : 
dyld: Library not loaded: /usr/local/lib/libmpfr.4.dylib
  Referenced from: /usr/local/libexec/gcc/x86_64-apple-darwin15.0.0/5.3.0/cc1
  Reason: image not found
gcc: internal compiler error: Abort trap: 6 (program cc1)
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://gcc.gnu.org/bugs.html> for instructions.
