### ISSUE TITLE
ICU init failed: U_FILE_ACCESS_ERROR on (open)SUSE

### ISSUE THREAD

**Issue by jeroenooms** [Rexamine/stringi#170]
I'm seeing [these problems](http://pastebin.com/raw.php?i=2d7vYWf8) on some servers (e.g. opensuse):

```
[  142s] ** preparing package for lazy loading
[  143s] ** help
[  143s] *** installing help indices
[  144s] ** building package indices
[  145s] ** testing if installed package can be loaded
[  145s] Error in dyn.load(file, DLLpath = DLLpath, ...) :
[  145s]   ICU init failed: U_FILE_ACCESS_ERROR
[  145s] Error: loading failed
```

I think the problem is that you are [overriding](https://github.com/cran/stringi/blob/master/src/stri_stringi.cpp#L260) the location of icudt even when linked against system ICU. I think you should only be calling `stri_set_icu_data_directory` when the package has been built with the bundled ICU.

Perhaps something like

```c
#ifdef UCONFIG_USE_LOCAL
   stri_set_icu_data_directory((char*)*(char**)(dll) /* dll->path */);
#endif
```

**Comment by gagolews** [comment]
Thanks, at least I'll have got stringi tested on many platforms. :)

I need full `./configure`'s output to diagnose that.

setDataDirectory shouldn't be the case here, as according to ICU manual, if a icudt.dat file is not found, bundled icudata (libicudata) is used.

I suspect that suse comes with incomplete icudata itself. Looking at [libicu53](http://software.opensuse.org/package/libicu53_1) rpm, you can see that `libicudata` is of very small size (typically it should be ca. 20 MB). So first please check your libicu's size. If it is the case, either recompile icu or build stringi with `--disable-pkg-config`.

And now you see the price of using system icu :)

**Comment by jeroenooms** [comment]
I don't have a suse machine available right now. Are these logs any help? [x86](https://build.opensuse.org/package/live_build_log/home:jeroenooms:opencpu-1.5/opencpu/openSUSE_13.2/i586) and [x64](https://build.opensuse.org/package/live_build_log/home:jeroenooms:opencpu-1.5/opencpu/openSUSE_13.2/x86_64).

**Comment by jeroenooms** [comment]
Oops sorry these logs are for the build without system ICU (which also fails). Let me get you the build log for the one with icu.

**Comment by gagolews** [comment]
In the attached build logs you get a download error. Cannot do anything about that.

As for suse, funny, there's a separate `libicu53_1-ledata-53.1-2.3.2` rpm. Make sure if it is indeed used. Also, strange, it is installed before `libicu53_1-53.1-2.3.2` - maybe the second rpm overwrites `libicudata`? If so, this is not my fault - you have a misconfigured build envir...

**Comment by gagolews** [comment]
BTW, if you got a blocked network conn on some system, why not installing stringi directly from github? In such a case, icudt is included in the source bundle - it will be copied from this local repo on install.

**Comment by jeroenooms** [comment]
I suspect that suse, like yourself, ships `icudt.dat` separately from `libicu` in the installation, but it can't find it because you are overriding `stri_set_icu_data_directory`.

**Comment by gagolews** [comment]
OK, I'll apply a patch soon (it is harmless anyway) and we'll see if it works.

**Comment by jeroenooms** [comment]
So how do I build the source package with batteries included? I tried:

```sh
git clone https://github.com/Rexamine/stringi/
R CMD build stringi
```

But that gives me the same thing as the CRAN version?

**Comment by gagolews** [comment]
```
R CMD INSTALL stringi --configure.args='--disable-pkg-config'
```

**Comment by gagolews** [comment]
Ah, you mean building the package -- you should edit `.Rinstignore` manually and get rid of `src/icu55/data` entry

**Comment by jeroenooms** [comment]
And that will automatically find it, and not download the files from the internet? So it can be compiled on a build server without internet access?

**Comment by gagolews** [comment]
Yes, `install.libs.R` first tries copying icudata from `src/icu55/data`.

**Comment by jeroenooms** [comment]
OK that makes the source package 23m, that is pretty big indeed. I'll first try it with your patch.

**Comment by gagolews** [comment]
Commit 76d125a8bf90ce3fec3300479eea9ac2543b5d1c pushed - what about now?

**Comment by fungs** [comment]
I'm also getting this when installing as a dependency of ggplot2 on openSUSE 13.2
When I pull the source from Github (c5fdde3ecbe3cac29b0c1e5f0891c441afed65d1) and install as suggested, I'm getting the same error and the following output. Note the unknown option warning at the beginning.

```
R CMD INSTALL stringi --configure.args='--disable-pkg-config'
Warning: unknown option ‘--configure.args=--disable-pkg-config’
* installing to library ‘/local/home/johdro/R/x86_64-suse-linux-gnu-library/3.1’
* installing *source* package ‘stringi’ ...
configure: loading site script /usr/share/site/x86_64-unknown-linux-gnu
checking for local ICUDT_DIR... icu55/data
checking for R_HOME... /usr/lib64/R
checking for R... /usr/lib64/R/bin/R
checking for R >= 3.1.0... yes
checking for cat... /usr/bin/cat
checking for gcc... gcc -std=gnu99
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc -std=gnu99 accepts -g... yes
checking for gcc -std=gnu99 option to accept ISO C89... none needed
checking how to run the C preprocessor... g++ -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking elf.h usability... yes
checking elf.h presence... yes
checking for elf.h... yes
checking whether we are using the GNU C++ compiler... yes
checking whether g++ -std=c++11 accepts -g... yes
checking whether the C++ compiler supports the long long type... yes
checking whether the compiler implements namespaces... yes
checking whether the compiler supports Standard Template Library... yes
checking whether std::map is available... yes
checking for pkg-config... /usr/bin/pkg-config
checking with pkg-config for ICU4C installed... 53.1
checking for ICU4C >= 50... yes
checking for proper CPPFLAGS, LDFLAGS, and LIBS... done
checking whether we may build an ICU-based project... yes
checking for available ICU data library (ucnv, uloc, utrans)... yes
checking for available ICU data library (ucol)... yes
configure: creating ./config.status
config.status: creating src/Makevars
config.status: creating src/uconfig_local.h
config.status: creating src/install.libs.R

*** stringi configure summary:
    ICU_FOUND=1
    ICUDT_DIR=icu55/data
    STRINGI_CXXSTD=CXX_STD=CXX11
    STRINGI_CFLAGS= 
    STRINGI_CPPFLAGS=-I.   -UDEBUG -DNDEBUG -DU_HAVE_ELF_H
    STRINGI_CXXFLAGS= 
    STRINGI_LDFLAGS=-L/usr/lib64  
    STRINGI_LIBS=-licui18n -licuuc -licudata  

*** compiler settings used:
    CC=gcc -std=gnu99
    CPP=g++ -E
    LD=g++
    CFLAGS=-fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g 
    CPPFLAGS=-I/usr/local/include  -UDEBUG -DNDEBUG
    CXX=g++ -std=c++11
    CXXFLAGS=-fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g 
    LDFLAGS= 
    LIBS= 
```

```
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  ICU init failed: U_FILE_ACCESS_ERROR
```

Installed packages are

> Repository: OpenSUSE OSS
> Name: libicu53_1
> Version: 53.1-2.3.2
> Arch: x86_64
> Vendor: openSUSE

> Repository: OpenSUSE OSS
> Name: libicu53_1-ledata
> Version: 53.1-2.3.2
> Arch: noarch
> Vendor: openSUSE

> Repository: OpenSUSE OSS
> Name: libicu53_1-bedata
> Version: 53.1-2.3.2
> Arch: noarch
> Vendor: openSUSE

**Comment by gagolews** [comment]
`R CMD INSTALL --help` --> the option name is `--configure-args`.

OK, I will install opensuse on a VM and check it out.

**Comment by fungs** [comment]
I reran it with the correct option syntax but it throws the same error (+ some compiler macro warnings about depricated syntax).

**Comment by fungs** [comment]
> OK, I will install opensuse on a VM and check it out.

Even faster with docker:

    docker pull opensuse:13.2
    docker run -t -i opensuse:13.2 /bin/bash

**Comment by gagolews** [comment]
self-note: icudt53l.dat is in `/usr/share/icu/53.1/`

**Comment by gagolews** [comment]
Should be fixed now, please confirm.

Apparently, the suse icu pkg rpm builder hardcoded ICUDATA path during the lib build. @jeroenooms was right, I forced overriding this path, which lead to an error.

@fungs, BTW, re-compiling the package with changed `--disable-pkg-config` setting needs a `make clean` -- this can be done by passing `--preclean` to `R CMD INSTALL`.

**Comment by jeroenooms** [comment]
Did you test it with the suse ICU or does it only work with `--disable-pkg-config` and bundled ICU? The Suse build servers do not allow internet access so it won't be able to download icudt.

**Comment by gagolews** [comment]
I tested it with system ICU.

**Comment by jeroenooms** [comment]
Okay great, thanks. I'll do another build of my stack soon, hopefully it works now.

**Comment by fungs** [comment]
@gagolews: I can test on my machine next week, and I will report.

**Comment by jlehtoma** [comment]
Had the same problem with openSUSE 13.2 Tumbleweed. Cloning stringi 0.5-3 from GitHub and installing with

```
R CMD INSTALL stringi --configure.args='--disable-pkg-config'
``` 

worked for me.

**Comment by gagolews** [comment]
Added a Docker opensuse testbed in #173, works for me.

**Comment by fungs** [comment]
I can also confirm that it works now. Thanks!
