### ISSUE TITLE
unable to compile stringi

### ISSUE THREAD

**Issue by gsaray101** [Rexamine/stringi#171]
I am on linux 64 bit, and trying to compile stringi, I keep getting this error:

checking for elf.h... no
checking whether the C++ compiler supports the long long type... no
*** stringi cannot be built. Upgrade your C++ compiler's settings

how do you get around this, how do you compile stringi in linux so that it works?

**Comment by gagolews** [comment]
Possible duplicate of #169, please verify.

**Comment by gsaray101** [comment]
Yes, thank u. That resolved my problem
