### ISSUE TITLE
stringi compile fails on new linux Mageia 5

### ISSUE THREAD

**Issue by paulb20** [Rexamine/stringi#179]
Goes through the complete compilation process then fails at: ICU init failed: U_FILE_ACCESS_ERROR

This of course disables huge chunks of the hadleyverse. And therefore breaks my scripts.

System ICU is version 53.1 - they have taken a long time as Mageia is a more 'stable' distro than some and it was transition to enable efi installs.

**Comment by gagolews** [comment]
did you try the most recent git version?

**Comment by paulb20** [comment]
library(devtools)
install(github("Rexamine/stringi")
Downloading gihub repo Rexamine/stringi@master
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck - vI[[i]]:
there is no package called 'stringr'
.... And of course stringr won't load without stringi so a dependency circle

**Comment by gagolews** [comment]
```
cd /tmp
git clone https://github.com/Rexamine/stringi.git
R CMD INSTALL stringi
```

**Comment by paulb20** [comment]
still working - it's a netbook so compilation not immediate

ICU_FOUND=1
UCUDT_DIR=ICU55/data
STRINGI_CXXSTD=CXXSTD=CXX11
STRINGI_CFLAGS=
STRINGI_CPPFLAGS=I.  -UDEBUG -DNDEBUG -DEHAVE_ELF_H
STRINGI_CXXFLAGS=
STRINGI_LDFLAGS=-L/usr/lib
STRINGI_LIBS=-licui18n -licuuc -licudata

**Comment by paulb20** [comment]
Has worked!!!

**Comment by gagolews** [comment]
OK, thanks for the report.

**Comment by paulb20** [comment]
And that enables stringr and ggplot2 to install too. Thanks for the help.
