### ISSUE TITLE
stri_c warns incorrectly (recycling rule) when using more than 2 elements.

### ISSUE THREAD

**Issue by singmann** [Rexamine/stringi#180]
When using more than two elements a warning is triggered even if the longer object length **is** a multiple of shorter object length. This erroneous warning is potentially connected to #174.
```
> stri_c("a", c("x", "y"), "b")
[1] "axb" "ayb"
Warning message:
In stri_c("a", c("x", "y"), "b") :
  longer object length is not a multiple of shorter object length
```

**Comment by gagolews** [comment]
Thanks for the report, it seems that the testthat package now ignores warnings generated by `test_that()` -- I haven't got them reported... Bugfix on the way.
