### ISSUE TITLE
Weird replacements with `stri_replace_all_regex`

### ISSUE THREAD

**Issue by gagolews** [Rexamine/stringi#181]
```
> stri_replace_all_regex("A", "^(.*)$", "ONE($1) TWO($1) THREE($1)")
[1] "ONE(A) TWO(A) THREE(A)"
> stri_replace_all_regex("A", "(.*)", "ONE($1) TWO($1) THREE($1)")
[1] "ONE(A) TWO(A) THREE(A)ONE() TWO() THREE()"
```

**Comment by gagolews** [comment]
See also https://github.com/hadley/stringr/issues/86

**Comment by gagolews** [comment]
We have:

```
> stri_extract_all_regex("A", ".*")
[[1]]
[1] "A" "" 
```

**Comment by gagolews** [comment]
OK, it's not a bug, it's a feature. `java.util.regex` behaves exactly like that, too:

```
Enter your regex: .*
Enter input string to search: A
I found the text "A" starting at index 0 and ending at index 1.
I found the text "" starting at index 1 and ending at index 1.
```

**Comment by petermeissner** [comment]
Will this *finding no-character when searching for any-character* persist? While feature it might be it is startling and actually does not come very handy.

**Comment by gagolews** [comment]
Yes, it will persist as it is default in ICU. If you want different behavior in stringr (e.g, if stringr=0.6 had something like dotall=TRUE both for TRE and PERL /I'm unsure/), ask @hadley

**Comment by gagolews** [comment]
Nope, `perl` also has dotall=FALSE in base R

```
> grep(".", "\n")
[1] 1
> grep(".", "\n", perl=TRUE)
integer(0)
```

**Comment by petermeissner** [comment]
I think the last two comments got a little mixed up and should have gone here: https://github.com/hadley/stringr/issues/69

**Comment by petermeissner** [comment]
There is still some behavior of dot (in stringi) that I want to point out and find inconsistent:

```r
stri_count( c("", "a", "aa"), regex = ".*")
## [1] 0 2 2
```

Shouldn't it be either:  *0 1 2* or 1 2 3 ?

**Comment by gagolews** [comment]
@petermeissner, this is again something generated by ICU regex engine and is totally compatible with Java regexes...
