### ISSUE TITLE
stringi-0.5-5 can't link system icu library when compiling with gcc 4.9.x

### ISSUE THREAD

**Issue by peti** [Rexamine/stringi#182]
I'm packaging `stringi` for the NixOS Linux distribution. Version 0.5-5 used to work just fine until we updated to gcc 4.9.x. Since then, the `configure` test that tries to find the system `icu` library fails with the following linker error:

    configure:4152: checking with pkg-config for ICU4C installed
    configure:4165: result: 55.1
    configure:4169: checking for ICU4C >= 50
    configure:4181: result: yes
    configure:4185: checking for proper CPPFLAGS, LDFLAGS, and LIBS
    configure:4190: result: done
    configure:4207: checking whether we may build an ICU-based project
    configure:4230: /nix/store/9yhhnkw0pdr99shq6bynqwqyjvpa27ki-gfortran-wrapper-4.8.5/bin/g++ -std=c++11 -o conftest -g -O2    -UDEBUG -DNDEBUG -I/nix/store/ldsridz6d677a8h24lp7bz7jriiah8zv-icu4c-55.1/include    -L/nix/store/ldsridz6d677a8h24lp7bz7jriiah8zv-icu4c-55.1/lib  conftest.cpp   -licui18n -licuuc -licudata  >&5
    /nix/store/ldsridz6d677a8h24lp7bz7jriiah8zv-icu4c-55.1/lib/libicui18n.so: undefined reference to `__cxa_throw_bad_array_new_length@CXXABI_1.3.8'
    collect2: error: ld returned 1 exit status
    configure:4230: $? = 1
    configure: failed program was:
    | /* confdefs.h */
    | #define PACKAGE_NAME "stringi"
    | #define PACKAGE_TARNAME "stringi"
    | #define PACKAGE_VERSION "0.5"
    | #define PACKAGE_STRING "stringi 0.5"
    | #define PACKAGE_BUGREPORT "stringi@rexamine.com"
    | #define PACKAGE_URL ""
    | #define STDC_HEADERS 1
    | #define HAVE_SYS_TYPES_H 1
    | #define HAVE_SYS_STAT_H 1
    | #define HAVE_STDLIB_H 1
    | #define HAVE_STRING_H 1
    | #define HAVE_MEMORY_H 1
    | #define HAVE_STRINGS_H 1
    | #define HAVE_INTTYPES_H 1
    | #define HAVE_STDINT_H 1
    | #define HAVE_UNISTD_H 1
    | #define HAVE_NAMESPACES /**/
    | #define HAVE_STL /**/
    | /* end confdefs.h.  */
    | 
    |       #include <unicode/unistr.h>
    |       #include <unicode/uvernum.h>
    |       #include <unicode/ptypes.h>
    |       #include <unicode/uchar.h>
    |       #include <unicode/utypes.h>
    |       #include <stdio.h>
    |       using namespace icu;
    | 
    |       int main() {
    |         // base tests
    |         UnicodeString x("abc");
    |         x = x+x;
    |         printf(U_ICU_VERSION);
    | 
    |         return 0;
    |       }
    | 
    configure:4237: result: no

My guess is that this issue is not specific to NixOS, but it's caused by the new gcc, really. Do you happen to have an idea how to remedy this error?

**Comment by gagolews** [comment]
Did you try to recompile the ICU library?

**Comment by peti** [comment]
Hmm, II'm not sure what happened yet, but it appears that we're building icu with gcc 4.9.x, but R is still using gfortran 4.8.x. I'll need to take a closer look at this. Thank you for the quick response.

**Comment by gagolews** [comment]
check out `<R_INST_DIRECTORY>/etc/Makeconf` for compiler settings & more

**Comment by gagolews** [comment]
And by the way, you may also get problems compiling other R packages => recompile R

**Comment by peti** [comment]
The bug was in our code. Sorry for the false report!
