### ISSUE TITLE
Incorrect length/multiple warning

### ISSUE THREAD

**Issue by pitakakariki** [Rexamine/stringi#185]
I don't think this warning message is correct:

    stringi::stri_c(c("a", "d"), ".", "c")
    [1] "a.c" "d.c"
    Warning message:
    In stringi::stri_c(c("a", "d"), ".", "c") :
      longer object length is not a multiple of shorter object length

**Comment by gagolews** [comment]
Already fixed in https://github.com/Rexamine/stringi/issues/180
