### ISSUE TITLE
stri_c throwing possible unexpected warning

### ISSUE THREAD

**Issue by DaveHastie** [Rexamine/stringi#191]
Using stringi_0.5-5 in R 3.2.2 on MacOSX Yosemite.

The following example
> stringi::stri_c("abc", 1:3)
[1] "abc1" "abc2" "abc3"

works as expected. However, if I put multiple atomic vectors into the function as well as a single vector of length greater than 1, I get an unexpected incompatible lengths warning:
> stringi::stri_c("abc", "xyz", 1:3)
[1] "abcxyz1" "abcxyz2" "abcxyz3"
Warning message:
In stringi::stri_c("abc", "xyz", 1:3) :
  longer object length is not a multiple of shorter object length

**Comment by gagolews** [comment]
Already fixed in https://github.com/Rexamine/stringi/issues/180
