### ISSUE TITLE
How can I install the stringi package on windows from the local repository?

### ISSUE THREAD

**Issue by seoseungwoo** [Rexamine/stringi#192]
Hello,
I use the non-available internet computer(cannot connect the internet)
I download the package from another computer, and burnt DVD then install the my computer
But, When I install the stringi package, I fail to install due to icudt55l.zip
I search the Google and stackoverflow etc, I see the solution is
http://stackoverflow.com/questions/27553452/how-to-install-stringi-library-from-archive-and-install-the-local-icu52l-zip

I execute the next code
install.packages("d:/aa/stringi_0.5-5.tar.gz",repos=NULL,configure.vars="ICUDT_DIR=d:/aa/icudt55l.zip")

But I fail to install and see the same error.
How can I install the stringi package??(package file(tar.gz) and icudtt55l.zip file are downloaded)

My computer OS is windows7.
Please Help me. I want to install stringi package..

**Comment by gagolews** [comment]
what about `"ICUDT_DIR='d:/aa/'"` ?

You may copy the icu data file manually after the package install (installed_package_folder `stringi/libs`)

**Comment by seoseungwoo** [comment]
"d:/aa" is location of icudt55l.zip
If I execute install.packages("d:/aa/stringi_0.5-5.tar.gz"), I fail to install due to icu data file.

what's the install method that without icu data file?

**Comment by gagolews** [comment]
can't you download the pre-compiled version of stringi from CRAN? (.zip file)

R 3.1 https://cran.r-project.org/bin/windows/contrib/3.1/stringi_0.5-5.zip

R 3.2 https://cran.r-project.org/bin/windows/contrib/3.2/stringi_0.5-5.zip

R 3.3 https://cran.r-project.org/bin/windows/contrib/3.3/stringi_0.5-5.zip

**Comment by gagolews** [comment]
the you `install.packages('.....zip')`

**Comment by seoseungwoo** [comment]
Thx a lot, install completely for your comment.
