### ISSUE TITLE
Documentation quibble for .

### ISSUE THREAD

**Issue by hadley** [Rexamine/stringi#196]
`?"stringi-search-regex"` says that `.` matches any character, but that's clearly not true:

```R
stringi::stri_detect("\n", regex = ".")
#> [1] FALSE
```

Can you give a more precise definition? Are there any other characters that don't match apart from `\n`?

**Comment by gagolews** [comment]
I will clarify it. http://userguide.icu-project.org/strings/regexp --> 

> 	UREGEX_DOTALL 	If set, a "." in a pattern will match a line terminator in the input text. By default, it will not. Note that a carriage-return / line-feed pair in text behave as a single line terminator, and will match a single "." in a RE pattern.
Line terminators are  \u000a, \u000b, \u000c, \u000d, \u0085, \u2028, \u2029 and the sequence \u000d \u000a.
