### ISSUE TITLE
stri_opts_regex() doesn't have locale parameter?

### ISSUE THREAD

**Issue by hadley** [Rexamine/stringi#197]
What locale does it use for case insensitive matching?

**Comment by gagolews** [comment]
The current default one, see `stri_locale_get()`

**Comment by gagolews** [comment]
But anyway, ICU regex matcher is not as intelligent as the one collator (`col`)-based, so you cannot match ß if you look for `ss` in German, say. Unicode normalization (NF...) should be needed here.

**Comment by hadley** [comment]
Thanks!
