### ISSUE TITLE
Add "mixed" argument to stri_sort/stri_order

### ISSUE THREAD

**Issue by DavidArenburg** [Rexamine/stringi#202]
I think it could be very useful if `stri_sort` and `stri_order` could order mixed strings correctly. I'm not sure if this should be a default or as an additional argument, but if the following would return the correct result it could be great IMO

```r
stringi::stri_sort(c("a 10", "a 2"))
## [1] "a 10" "a 2" 
```

**Comment by gagolews** [comment]
Did you mean:

```
> stringi::stri_sort(c("a 10", "a 2"), list(numeric=TRUE))
[1] "a 2"  "a 10"
```

?

**Comment by DavidArenburg** [comment]
Interesting. I'm not sure if this is very well documented, but I'll keep that in mind.
Thanks.

**Comment by DavidArenburg** [comment]
As a side note, why the following sorts the string in a decreasing order if the `decreasing = FALSE` by default? `stringi::stri_sort(as.character(1:3), list(numeric = TRUE))`. Is that intended?

**Comment by gagolews** [comment]
this list is a named arg, I forgot to add `opts=list(....)`, sorry! I updated the example

**Comment by DavidArenburg** [comment]
Thanks, Very nice. I think it could be very useful to have some examples with `opts_collator` in the examples in the documentation. I doubt many people know `stringi` can do a mixed sort.

**Comment by gagolews** [comment]
You can pull a push request if you want :)

**Comment by DavidArenburg** [comment]
Btw, it seems like the `...` passes `numeric` directly to the `opts_collector`, so just `stringi::stri_sort(as.character(1:3), numeric = TRUE)` works too.
