### ISSUE TITLE
Turkish ı problem

### ISSUE THREAD

**Issue by vezir** [Rexamine/stringi#204]
There is a Turkish 'ı' problem.

This output is correct
> string <- "inek"
> str_to_upper(string, locale = "tr")
[1] "İNEK"

But this is not
> String <- "İNEK"
> str_to_lower(String, locale = "tr")
[1] "ınek"
This one must be 'inek'. In other words 'İ' must be converted to 'i' not 'ı'

**Comment by bartektartanus** [comment]
I think this is the ICU library bug, not ours...

**Comment by gagolews** [comment]
This is definitely ICU related. Which ICU version do you use? `stri_info(TRUE)`?

I got:

```
> stringi::stri_info(TRUE)
[1] "stringi_1.0.2 (pl_PL.UTF-8; ICU4C 52.1 [system]; Unicode 6.3)"
> library(stringi)
> string <- "inek"
> stri_trans_toupper(string, locale = "tr")
[1] "İNEK"
> String <- "İNEK"
> stri_trans_tolower(String, locale = "tr")
[1] "inek"
> String <- "INEK"
> stri_trans_tolower(String, locale = "tr")
[1] "ınek"
```

**Comment by vezir** [comment]
> stri_info(TRUE)
[1] "stringi_1.0.1 (en_US.windows-1254; ICU4C 55.1 [bundle]; Unicode 7.0)"
