### ISSUE TITLE
Unable to install stringi

### ISSUE THREAD

**Issue by puneetduain** [Rexamine/stringi#206]
/usr/lib64/R/bin/R CMD INSTALL stringi_0.5-5.tar.gz --configure-args='ICUDT_DIR=/staging/'

Error Log
---------
checking whether the C++ compiler supports the long long type... no
*** trying with disabled C++11 compiler
checking whether the C++ compiler supports the long long type... no
*** verify your C++ compiler's abilities (long long, STL, etc. support)
ERROR: configuration failed for package ‘stringi’

R CMD INSTALL stringi_0.5-5.tar.gz --configure-args='ICUDT_DIR=/staging/' --configure-args='--disable-cxx11'

Error Log
---------
checking for elf.h... yes
checking whether we are using the GNU C++ compiler... yes
checking whether g++ -m64 accepts -g... yes
checking whether the C++ compiler supports the long long type... no
*** verify your C++ compiler's abilities (long long, STL, etc. support)
ERROR: configuration failed for package ‘stringi’
*

**Comment by puneetduain** [comment]
It's not installing on one machine, on other it gets installed without issues. Output of below commands on RHEL 65 is same
R CMD config CXX1X
cat /usr/lib64/R/etc/Makeconf | grep CXX1X

**Comment by gagolews** [comment]
I need more info to diagnose the problem: please copy-paste the generated `config.log`, `config.status` files

**Comment by gagolews** [comment]
also, `g++ -v` output pls

**Comment by puneetduain** [comment]
Using built-in specs.
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-languages=c,c++,objc,obj-c++,java,fortran,ada --enable-java-awt=gtk --disable-dssi --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-1.5.0.0/jre --enable-libgcj-multifile --enable-java-maintainer-mode --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --disable-libjava-multilib --with-ppl --with-cloog --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.4.7 20120313 (Red Hat 4.4.7-4) (GCC)

**Comment by puneetduain** [comment]
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking elf.h usability... yes
checking elf.h presence... yes
checking for elf.h... yes
checking whether we are using the GNU C++ compiler... yes
checking whether g++ -m64 -std=c++0x accepts -g... yes
checking whether the C++ compiler supports the long long type... no
*** trying with disabled C++11 compiler
checking whether we are using the GNU C++ compiler... yes
checking whether g++ -m64 accepts -g... yes
checking whether the C++ compiler supports the long long type... no
*** verify your C++ compiler's abilities (long long, STL, etc. support)
ERROR: configuration failed for package ‘stringi’

**Comment by gagolews** [comment]
this is a quite old gcc version

you can try passing `--configure-args='--with-extra-cxxflags="-std=gnu++0x"'`

**Comment by puneetduain** [comment]
Still Same issue...
The same has worked on 7 different servers with exactly same version but not working on this which is very critical

**Comment by gagolews** [comment]
unpack the source targz and run `R CMD INSTALL unpacked_dir`; I need the config.log, config.status files..

**Comment by puneetduain** [comment]
I cannot upload a file, so I compared the file console.log file between the system where it is failing and where it is running and this was the difference (error)

configure:3851: result: yes
configure:3885: checking whether the C++ compiler supports the long long type
configure:3905: g++ -m64 -std=c++0x -o conftest -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic  -I/usr/local/include  -UDEBUG -DNDEBUG   conftest.cpp   >&5
In file included from conftest.cpp:20:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/iostream:39:28: error: bits/c++config.h: No such file or directory
In file included from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/ios:42,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/ostream:40,

config.status didn't generate...Will it suffice?

**Comment by gagolews** [comment]
The problem is definitely on your side `  error: bits/c++config.h: No such file or directory` - check your C++ compiler etc., I'm afraid I can't help you with that

**Comment by gagolews** [comment]
see, e.g., http://stackoverflow.com/questions/4643197/missing-include-bits-cconfig-h-when-cross-compiling-64-bit-program-on-32-bit

**Comment by puneetduain** [comment]
Thanks for working with me on this...Thought to share the resolution...it was listdc++-devel 64-bit rpm that was not installed...

**Comment by gagolews** [comment]
I'm glad you resolved the issue. Thanks for the info!

**Comment by wleoncio** [comment]
> listdc++-devel 64-bit rpm that was not installed...

Just a quick headsup, spelling is probably [libstdc++-devel](https://pkgs.org/download/libstdc++-devel).
