### ISSUE TITLE
The installation issue for Stringi

### ISSUE THREAD

**Issue by jial2** [Rexamine/stringi#208]
Hi,
I tried to install stringi into R version 3.2.1. I tried the ways people suggested, it works with binary installation.
install.packages("stringi",type="mac.binary")
Unfortunately when I install S4Vectors package, I realized that it wasn't completely installed. I found this message as below.

installing the source package ‘stringi’

trying URL 'http://watson.nci.nih.gov/cran_mirror/src/contrib/stringi_1.0-1.tar.gz'
Content type 'application/octet-stream' length 3643002 bytes (3.5 MB)
==================================================
downloaded 3.5 MB

* installing *source* package ‘stringi’ ...
** package ‘stringi’ successfully unpacked and MD5 sums checked
checking for local ICUDT_DIR... icu55/data
checking for R_HOME... /Library/Frameworks/R.framework/Resources
checking for R... /Library/Frameworks/R.framework/Resources/bin/R
checking for R >= 3.1.0... yes
checking for cat... /bin/cat
/Library/Frameworks/R.framework/Resources/bin/config: line 150: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 151: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 152: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 153: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 269: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 150: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 151: make: command not found
......
checking for gcc... /Library/Frameworks/R.framework/Resources/bin/config: line 269: make: command not found
no
checking for cc... no
checking for cl.exe... no
configure: error: in `/private/var/folders/9q/0p26y65x657301xptkm33lz56w2r8v/T/Rtmp71Hadj/R.INSTALL71484304202/stringi':
configure: error: no acceptable C compiler found in $PATH
See `config.log' for more details
ERROR: configuration failed for package ‘stringi’
* removing ‘/Users/jial2/Library/R/3.2/library/stringi’
* restoring previous ‘/Users/jial2/Library/R/3.2/library/stringi’

Here is sessioninfo
> sessionInfo()
R version 3.2.1 (2015-06-18)
Platform: x86_64-apple-darwin10.8.0 (64-bit)
Running under: OS X 10.8.5 (Mountain Lion)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] BiocInstaller_1.20.1 devtools_1.9.1       RCurl_1.95-4.7       bitops_1.0-6         zoo_1.7-12          

loaded via a namespace (and not attached):
 [1] lattice_0.20-33 digest_0.6.8    grid_3.2.1      R6_2.1.1        magrittr_1.5    httr_1.0.0      stringi_0.5-5   curl_0.9.1     
 [9] tools_3.2.1     stringr_1.0.0   memoise_0.2.1  

It seems that it's installed in binary, but it actually has the problem.

Thanks for the help.

EL

**Comment by gagolews** [comment]
To build a source version of any R package, you have to install [Xcode](https://developer.apple.com/xcode/)
