### ISSUE TITLE
Stringi searches for libicu version 52 although 55 is installed

### ISSUE THREAD

**Issue by saeltz** [Rexamine/stringi#209]
I get this error message in latest RStudio on Ubuntu 15.10 with all packages up-to-date:
unable to load shared object '/usr/local/lib/R/site-library/stringi/libs/stringi.so':
libicui18n.so.52: cannot open shared object file: No such file or directory

I checked that libicui18n version 55 is installed. The above searches for version 52 which fails. How to fix?

**Comment by gagolews** [comment]
did you try to reinstall/recompile the package?

**Comment by saeltz** [comment]
That worked like a charm now. Tried it back in October with stringi 0.5-3 and that didn't help for installing ggplot2. Must have been to do with Ubuntu 15.10 Upgrade, R and stringi updates. Thanks!
