### ISSUE TITLE
Stringi doesn't compile on fedora 23

### ISSUE THREAD

**Issue by joelthelion** [Rexamine/stringi#211]
With the latest git revision:

```bash
[jschaerer@kiwi stringi]$ git pull && ./configure 
Already up-to-date.
checking for local ICUDT_DIR... icu55/data
checking for R_HOME... /usr/lib64/R
checking for R... /usr/lib64/R/bin/R
checking for R >= 3.1.0... yes
checking for cat... /usr/bin/cat
checking for gcc... gcc -m64
checking whether the C compiler works... no
configure: error: in `/home/jschaerer/workspace/stringi':
configure: error: C compiler cannot create executables
See `config.log' for more details
```

Attached the full [config.log](https://github.com/Rexamine/stringi/files/68543/config.log.txt) (renamed config.log.txt to cope with github's limitations). I tried removing the offending options, but then I run into other issues. I suspect someone with a better understanding of the autotools would be far more efficient at fixing this.

**Comment by gagolews** [comment]
Check if your gcc compiler works. Did you install it? I use Fedora for the package development.

**Comment by joelthelion** [comment]
@gagolews : I use g++ for my own development and it works fine... I'm probably missing some package specific to C or R? I'll investigate more and report back.

Just to make sure: are you using fedora 23? With 22 it used to work fine.

**Comment by joelthelion** [comment]
I have "C Development Tools and Libraries" and "Development Tools" package groups installed, as well as the obvious (R-devel, and probably a few more I've needed).

**Comment by joelthelion** [comment]
I have the same error when I run the command manually:

```
[jschaerer@kiwi coolstuff]$ gcc -m64 -V
gcc: error: unrecognized command line option ‘-V’
```

I couldn't find a trace of this option in the gcc man page. I also tried on a Debian system to see if it used to be an option in older versions of gcc, but I have the same error. Do you know what that option is for, and why it is in the configure script?

**Comment by gagolews** [comment]
what about `gcc -v` (lower case v)?

**Comment by joelthelion** [comment]
That works:

```
[jschaerer@kiwi stringi]$ gcc -v
Using built-in specs.
COLLECT_GCC=/usr/bin/gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/5.3.1/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,objc,obj-c++,fortran,ada,go,lto --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array --disable-libgcj --with-isl --enable-libmpx --enable-gnu-indirect-function --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 5.3.1 20151207 (Red Hat 5.3.1-2) (GCC) 
```

**Comment by gagolews** [comment]
did you try to compile some other package, e.g., `fastcluster` (via install.packages)

**Comment by gagolews** [comment]
the error via configure is here:

```
configure:2780: gcc -m64 -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic  -I/usr/local/include  -UDEBUG -DNDEBUG   conftest.c   >&5
gcc: error: /usr/lib/rpm/redhat/redhat-hardened-cc1: No such file or directory
```

**Comment by gagolews** [comment]
what's that `-specs=/usr/lib/rpm/redhat/redhat-hardened-cc1` stuff ?

**Comment by gagolews** [comment]
checkout `/usr/lib64/R/etc/Makeconf` or `Renvir` or sth

**Comment by joelthelion** [comment]
OK, with your help I was able to figure it out. The culprit was this redhat-hardened-cc1, which is mentioned in /usr/lib64/R/etc/Makeconf. To get it I had to install ```redhat-rpm-config```. I think this is a bug in the fedora packaging of R-core or R-core-devel. Since it is needed for compiling packages, it should probably be an explicit dependency. What do you think?

In any case sorry for the noise, and thanks for your time. I hope this will help other people in the future.

**Comment by gagolews** [comment]
I guess you should contact the R/Fedora packaging guys, they must have some bug repo tool.
