### ISSUE TITLE
stri_detect_regex fails to detect some kinds of punctuation

### ISSUE THREAD

**Issue by richierocks** [Rexamine/stringi#213]
From `?regex`:

> Certain named classes of characters are predefined. Their interpretation depends 
> on the locale (see locales); the interpretation below is that of the POSIX locale.
> 
> [:punct:]
>     Punctuation characters:
>     ! " # $ % & ' ( ) * + , - . / : ; < = > ? @ [ \ ] ^ _ ` { | } ~.

I expect all values of `x` below to be matched.

```{r}
x<- c("!", "\"", "#", "$", "%", "&", "'", "(", ")", "*", "+", ",", "-", ".", "/", ":", ";", "<", "=", ">", "?", "@", "[", "\\", "]", "^", "_", "`", "{", "|", "}", "~")
```

This is true using `grepl`:

```{r}
x[!grepl("[[:punct:]]", x)]
## character(0)
```

but not using `stri_detect_regex`:

```{r}
x[!stri_detect_regex(x, "[[:punct:]]")]
## [1] "$" "+" "<" "=" ">" "^" "`" "|" "~"
```

I wondered if this might be a locale problem, but it remains even when I set `Sys.setlocale(locale = "C")`.

**Comment by gagolews** [comment]
?regex has nothing to do with ICU, on which stringi is based.

Check out, e.g., http://stackoverflow.com/questions/26348643/r-regex-with-stringi-icu-why-is-a-considered-a-non-punct-character
