### ISSUE TITLE
stri_replace_all_regex() with multi-hyphenated words

### ISSUE THREAD

**Issue by tpaskhalis** [Rexamine/stringi#215]
When replacing hyphens in words that contain several of them, I noticed this strange behaviour. Is
this something that should be expected when dealing with single-character words and `\w`? `\b` seems to fix the issue, but with `\w` it still looks odd.

```
> stri_replace_all_regex("a-a-a-a", "(\\w)[\\p{Pd}](\\w)", "$1 $2")
[1] "a a-a a"
> stri_replace_all_regex("a-aa-aa-a", "(\\w)[\\p{Pd}](\\w)", "$1 $2")
[1] "a aa aa a"
> stri_replace_all_regex("a-aa-a-aa", "(\\w)[\\p{Pd}](\\w)", "$1 $2")
[1] "a aa a-aa"
```

**Comment by gagolews** [comment]
It's a feature of all regex engines. By default, pattern matches cannot overlap. Perhaps you are looking for look-aheads/look-behinds: http://www.regular-expressions.info/lookaround.html
